name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '2.7'
            gemfile: 'rails_6_0'
          - ruby: '2.7'
            gemfile: 'rails_6_1'
          - ruby: '3.0'
            gemfile: 'rails_6_1'
          - ruby: '3.0'
            gemfile: 'rails_7_0'
          - ruby: '3.1'
            gemfile: 'rails_7_0'
          - ruby: '3.2'
            gemfile: 'rails_7_0'
          - ruby: '3.3'
            gemfile: 'rails_7_0'
          - ruby: '2.7'
            gemfile: 'rails_7_1'
          - ruby: '3.0'
            gemfile: 'rails_7_1'
          - ruby: '3.1'
            gemfile: 'rails_7_1'
          - ruby: '3.2'
            gemfile: 'rails_7_1'
          - ruby: '3.2'
            gemfile: 'rails_7_2'
          - ruby: '3.3'
            gemfile: 'rails_7_2'
          - ruby: '3.4'
            gemfile: 'rails_7_2'
          - ruby: '3.2'
            gemfile: 'rails_8_0'
          - ruby: '3.3'
            gemfile: 'rails_8_0'
          - ruby: '3.4'
            gemfile: 'rails_8_0'
          - ruby: '3.2'
            gemfile: 'rails_8_1'
          - ruby: '3.3'
            gemfile: 'rails_8_1'
          - ruby: '3.4'
            gemfile: 'rails_8_1'
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run test
        run: |
          set -xe
          bundle exec rake
